### ISSUE TITLE
App wont UP using Spring Boot 2.5.0

### ISSUE THREAD

**Issue by hendisantika** [xtremebiker/jsf-spring-boot#1]
Hi @xtremebiker , I try with Spring Boot 2.5.0 versi0n here https://github.com/hendisantika/spring-boot-prime-faces/blob/springboot2/pom.xml.

But, I won't come up.

Do You have any idea?

Thanks

**Comment by xtremebiker** [comment]
Hello, I've just seen your message. Everything I can tell you is that the code in my repo works with my versions, so maybe you could try tweaking my code for your own versions in order to get further info...

**Comment by hendisantika** [comment]
Hmmm .... maybe doesn't support latest version (2.5.0)

**Comment by muizer** [comment]
well, I just tried with Java 16, had some reflection issues there, after updating to Spring Boot 2.5.1 and adding the missing junit dependency everything worked like a charm!

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>

I propose to close this issue (and add the junit dependency instead). Next to that, one could add this to the .gitignore for IntelliJ peeps:

.idea/
*.iml

**Comment by xtremebiker** [comment]
> 
> 
> well, I just tried with Java 16, had some reflection issues there, after updating to Spring Boot 2.5.1 and adding the missing junit dependency everything worked like a charm!
> 
> ```
> 	<dependency>
> 		<groupId>junit</groupId>
> 		<artifactId>junit</artifactId>
> 		<version>4.12</version>
> 		<scope>test</scope>
> 	</dependency>
> ```
> 
> I propose to close this issue (and add the junit dependency instead). Next to that, one could add this to the .gitignore for IntelliJ peeps:
> 
> .idea/
> *.iml

Thank you for your work @muizer! Feel free to fork the repo, change it with the new Spring Boot version configuration and perform a pull request, I'll be happy to replace it with the new configuration!

**Comment by muizer** [comment]
@xtremebiker done :)
